### ISSUE TITLE
some things seems broken openrct2 0.3.2 cea5fab

### ISSUE THREAD

**Issue by Ande103** [oli414/StreamIntegrationPlugin#2]
Openrct2 version: 0.3.2 cea5fab

it seems that some things no longer work
this is what i found

!ducks get notification but no ducks are spawning

!explode get notification but peeps wont explode

!robinhood get notification but peeps explode

!mow get notification but nothing happens

!fix get notification but nothing happens

all weather commands get notification but won the scenario

!umbrellas, !balloons, !maps get notification but peeps explode

on multiplayer
almost the same as single player

no notifications

!setstaffname cant name staff member

!setcolor, !setname, !rainbow not working

**Comment by oli414** [comment]
Hi, thanks for checking out the plugin. Can you send me the `config_ffa.json` file from the Stream Integration Relay folder?

I'll investigate to see what the issue is!

Additionally, when did you last update/install the plugin? There were some changes to OpenRCT2 which required a new verison of the plugin:
https://github.com/oli414/StreamIntegrationPlugin/releases/tag/1.3

**Comment by Ande103** [comment]
first time trying the plugin so i have v1.3 of the plugin
awesome plugin by the way

[config_ffa.zip](https://github.com/oli414/StreamIntegrationPlugin/files/5787147/config_ffa.zip)

**Comment by oli414** [comment]
Thanks! I have a suspicion for what is going on since something similair has happened before when a cheat was added / removed so I'll check with the OpenRCT2 devs to see if that is the case again.

**Comment by Ande103** [comment]
Nice i hope it's an easy fix

I forgot to add that peeps name as viewer when joining doesn't work

**Comment by technopoet** [comment]
I'm still having these same issues - any update on what's causing them?

**Comment by oli414** [comment]
Can you try to play on develop instead of release? The current stable release version is not supported. You can download an older release of this plugin if you wish to play on the release version, but it either won't have the peep names working, or may significantly harm performance due to a bug in the early version of this plugin.

**Comment by technopoet** [comment]
Sure, I'll switch to the development build and see if that helps. Thanks!
